/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const UpsertWalletArgs = IDL.Record({
  'cryptoName' : IDL.Text,
  'network' : IDL.Text,
  'walletAddress' : IDL.Text,
  'isActive' : IDL.Bool,
  'iconUrl' : IDL.Text,
  'symbol' : IDL.Text,
});
export const WalletId = IDL.Nat;
export const CryptoWalletPublic = IDL.Record({
  'id' : WalletId,
  'cryptoName' : IDL.Text,
  'network' : IDL.Text,
  'walletAddress' : IDL.Text,
  'isActive' : IDL.Bool,
  'iconUrl' : IDL.Text,
  'symbol' : IDL.Text,
});
export const WithdrawalId = IDL.Nat;
export const InvestmentId = IDL.Nat;
export const DepositId = IDL.Nat;
export const PackageTier = IDL.Variant({
  'GENESIS' : IDL.Null,
  'VELOCITY' : IDL.Null,
  'MOMENTUM' : IDL.Null,
});
export const CreateInvestmentArgs = IDL.Record({
  'packageTier' : PackageTier,
  'amount' : IDL.Nat,
});
export const InvestmentStatus = IDL.Variant({
  'MATURED' : IDL.Null,
  'CANCELLED' : IDL.Null,
  'ACTIVE' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const InvestmentPublic = IDL.Record({
  'id' : InvestmentId,
  'status' : InvestmentStatus,
  'packageTier' : PackageTier,
  'maturityDate' : Timestamp,
  'userId' : UserId,
  'lastRoiAccrual' : Timestamp,
  'accumulatedBalance' : IDL.Nat,
  'amount' : IDL.Nat,
  'startDate' : Timestamp,
});
export const DepositStatus = IDL.Variant({
  'REJECTED' : IDL.Null,
  'PENDING' : IDL.Null,
  'CONFIRMED' : IDL.Null,
});
export const DepositPublic = IDL.Record({
  'id' : DepositId,
  'status' : DepositStatus,
  'packageTier' : PackageTier,
  'userId' : UserId,
  'confirmedAt' : IDL.Opt(Timestamp),
  'submittedAt' : Timestamp,
  'walletAddress' : IDL.Text,
  'adminNote' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'walletId' : WalletId,
});
export const ReferralCode = IDL.Text;
export const UserPublic = IDL.Record({
  'id' : UserId,
  'referralCode' : ReferralCode,
  'username' : IDL.Text,
  'email' : IDL.Text,
  'referredBy' : IDL.Opt(UserId),
  'registeredAt' : Timestamp,
});
export const WithdrawalStatus = IDL.Variant({
  'REJECTED' : IDL.Null,
  'PENDING' : IDL.Null,
  'APPROVED' : IDL.Null,
});
export const WithdrawalPublic = IDL.Record({
  'id' : WithdrawalId,
  'status' : WithdrawalStatus,
  'userId' : UserId,
  'destinationAddress' : IDL.Text,
  'processedAt' : IDL.Opt(Timestamp),
  'adminNote' : IDL.Opt(IDL.Text),
  'amount' : IDL.Nat,
  'requestedAt' : Timestamp,
});
export const Rank = IDL.Variant({
  'INFLUENCER' : IDL.Null,
  'ARBITRAGEUR' : IDL.Null,
  'NEXUS' : IDL.Null,
  'APEX' : IDL.Null,
  'GAME_CHANGER' : IDL.Null,
  'TRAILBLAZER' : IDL.Null,
  'VISIONARY' : IDL.Null,
  'TITAN' : IDL.Null,
  'CATALYST' : IDL.Null,
  'LUMINARY' : IDL.Null,
  'PIONEER' : IDL.Null,
  'STRATEGIST' : IDL.Null,
});
export const RegisterArgs = IDL.Record({
  'referralCode' : IDL.Opt(ReferralCode),
  'username' : IDL.Text,
  'email' : IDL.Text,
});
export const RequestWithdrawalArgs = IDL.Record({
  'destinationAddress' : IDL.Text,
  'amount' : IDL.Nat,
});
export const SubmitDepositArgs = IDL.Record({
  'packageTier' : PackageTier,
  'amount' : IDL.Nat,
  'walletId' : WalletId,
});

export const idlService = IDL.Service({
  'accrueAllRoi' : IDL.Func([], [], []),
  'adminAddAdmin' : IDL.Func([UserId], [], []),
  'adminAddWallet' : IDL.Func([UpsertWalletArgs], [CryptoWalletPublic], []),
  'adminApproveWithdrawal' : IDL.Func(
      [WithdrawalId, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'adminCancelInvestment' : IDL.Func([InvestmentId], [], []),
  'adminConfirmDeposit' : IDL.Func([DepositId, IDL.Opt(IDL.Text)], [], []),
  'adminCreateInvestment' : IDL.Func(
      [UserId, CreateInvestmentArgs],
      [InvestmentPublic],
      [],
    ),
  'adminDeleteWallet' : IDL.Func([WalletId], [], []),
  'adminListAdmins' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'adminListAllWallets' : IDL.Func(
      [],
      [IDL.Vec(CryptoWalletPublic)],
      ['query'],
    ),
  'adminListDeposits' : IDL.Func([], [IDL.Vec(DepositPublic)], ['query']),
  'adminListInvestments' : IDL.Func([], [IDL.Vec(InvestmentPublic)], ['query']),
  'adminListUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
  'adminListWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalPublic)], ['query']),
  'adminRejectDeposit' : IDL.Func([DepositId, IDL.Opt(IDL.Text)], [], []),
  'adminRejectWithdrawal' : IDL.Func([WithdrawalId, IDL.Opt(IDL.Text)], [], []),
  'adminRemoveAdmin' : IDL.Func([UserId], [], []),
  'adminUpdateWallet' : IDL.Func([WalletId, UpsertWalletArgs], [], []),
  'getDashboard' : IDL.Func(
      [],
      [
        IDL.Record({
          'referralCode' : ReferralCode,
          'totalInvested' : IDL.Nat,
          'rank' : Rank,
          'referralEarnings' : IDL.Nat,
          'accumulatedBalance' : IDL.Nat,
          'dailyRoiRate' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getMyDeposits' : IDL.Func([], [IDL.Vec(DepositPublic)], ['query']),
  'getMyInvestments' : IDL.Func([], [IDL.Vec(InvestmentPublic)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
  'getMyWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalPublic)], ['query']),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveWallets' : IDL.Func([], [IDL.Vec(CryptoWalletPublic)], ['query']),
  'register' : IDL.Func([RegisterArgs], [IDL.Bool], []),
  'requestWithdrawal' : IDL.Func(
      [RequestWithdrawalArgs],
      [WithdrawalPublic],
      [],
    ),
  'submitDeposit' : IDL.Func([SubmitDepositArgs], [DepositPublic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const UpsertWalletArgs = IDL.Record({
    'cryptoName' : IDL.Text,
    'network' : IDL.Text,
    'walletAddress' : IDL.Text,
    'isActive' : IDL.Bool,
    'iconUrl' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const WalletId = IDL.Nat;
  const CryptoWalletPublic = IDL.Record({
    'id' : WalletId,
    'cryptoName' : IDL.Text,
    'network' : IDL.Text,
    'walletAddress' : IDL.Text,
    'isActive' : IDL.Bool,
    'iconUrl' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const WithdrawalId = IDL.Nat;
  const InvestmentId = IDL.Nat;
  const DepositId = IDL.Nat;
  const PackageTier = IDL.Variant({
    'GENESIS' : IDL.Null,
    'VELOCITY' : IDL.Null,
    'MOMENTUM' : IDL.Null,
  });
  const CreateInvestmentArgs = IDL.Record({
    'packageTier' : PackageTier,
    'amount' : IDL.Nat,
  });
  const InvestmentStatus = IDL.Variant({
    'MATURED' : IDL.Null,
    'CANCELLED' : IDL.Null,
    'ACTIVE' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const InvestmentPublic = IDL.Record({
    'id' : InvestmentId,
    'status' : InvestmentStatus,
    'packageTier' : PackageTier,
    'maturityDate' : Timestamp,
    'userId' : UserId,
    'lastRoiAccrual' : Timestamp,
    'accumulatedBalance' : IDL.Nat,
    'amount' : IDL.Nat,
    'startDate' : Timestamp,
  });
  const DepositStatus = IDL.Variant({
    'REJECTED' : IDL.Null,
    'PENDING' : IDL.Null,
    'CONFIRMED' : IDL.Null,
  });
  const DepositPublic = IDL.Record({
    'id' : DepositId,
    'status' : DepositStatus,
    'packageTier' : PackageTier,
    'userId' : UserId,
    'confirmedAt' : IDL.Opt(Timestamp),
    'submittedAt' : Timestamp,
    'walletAddress' : IDL.Text,
    'adminNote' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'walletId' : WalletId,
  });
  const ReferralCode = IDL.Text;
  const UserPublic = IDL.Record({
    'id' : UserId,
    'referralCode' : ReferralCode,
    'username' : IDL.Text,
    'email' : IDL.Text,
    'referredBy' : IDL.Opt(UserId),
    'registeredAt' : Timestamp,
  });
  const WithdrawalStatus = IDL.Variant({
    'REJECTED' : IDL.Null,
    'PENDING' : IDL.Null,
    'APPROVED' : IDL.Null,
  });
  const WithdrawalPublic = IDL.Record({
    'id' : WithdrawalId,
    'status' : WithdrawalStatus,
    'userId' : UserId,
    'destinationAddress' : IDL.Text,
    'processedAt' : IDL.Opt(Timestamp),
    'adminNote' : IDL.Opt(IDL.Text),
    'amount' : IDL.Nat,
    'requestedAt' : Timestamp,
  });
  const Rank = IDL.Variant({
    'INFLUENCER' : IDL.Null,
    'ARBITRAGEUR' : IDL.Null,
    'NEXUS' : IDL.Null,
    'APEX' : IDL.Null,
    'GAME_CHANGER' : IDL.Null,
    'TRAILBLAZER' : IDL.Null,
    'VISIONARY' : IDL.Null,
    'TITAN' : IDL.Null,
    'CATALYST' : IDL.Null,
    'LUMINARY' : IDL.Null,
    'PIONEER' : IDL.Null,
    'STRATEGIST' : IDL.Null,
  });
  const RegisterArgs = IDL.Record({
    'referralCode' : IDL.Opt(ReferralCode),
    'username' : IDL.Text,
    'email' : IDL.Text,
  });
  const RequestWithdrawalArgs = IDL.Record({
    'destinationAddress' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const SubmitDepositArgs = IDL.Record({
    'packageTier' : PackageTier,
    'amount' : IDL.Nat,
    'walletId' : WalletId,
  });
  
  return IDL.Service({
    'accrueAllRoi' : IDL.Func([], [], []),
    'adminAddAdmin' : IDL.Func([UserId], [], []),
    'adminAddWallet' : IDL.Func([UpsertWalletArgs], [CryptoWalletPublic], []),
    'adminApproveWithdrawal' : IDL.Func(
        [WithdrawalId, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'adminCancelInvestment' : IDL.Func([InvestmentId], [], []),
    'adminConfirmDeposit' : IDL.Func([DepositId, IDL.Opt(IDL.Text)], [], []),
    'adminCreateInvestment' : IDL.Func(
        [UserId, CreateInvestmentArgs],
        [InvestmentPublic],
        [],
      ),
    'adminDeleteWallet' : IDL.Func([WalletId], [], []),
    'adminListAdmins' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'adminListAllWallets' : IDL.Func(
        [],
        [IDL.Vec(CryptoWalletPublic)],
        ['query'],
      ),
    'adminListDeposits' : IDL.Func([], [IDL.Vec(DepositPublic)], ['query']),
    'adminListInvestments' : IDL.Func(
        [],
        [IDL.Vec(InvestmentPublic)],
        ['query'],
      ),
    'adminListUsers' : IDL.Func([], [IDL.Vec(UserPublic)], ['query']),
    'adminListWithdrawals' : IDL.Func(
        [],
        [IDL.Vec(WithdrawalPublic)],
        ['query'],
      ),
    'adminRejectDeposit' : IDL.Func([DepositId, IDL.Opt(IDL.Text)], [], []),
    'adminRejectWithdrawal' : IDL.Func(
        [WithdrawalId, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'adminRemoveAdmin' : IDL.Func([UserId], [], []),
    'adminUpdateWallet' : IDL.Func([WalletId, UpsertWalletArgs], [], []),
    'getDashboard' : IDL.Func(
        [],
        [
          IDL.Record({
            'referralCode' : ReferralCode,
            'totalInvested' : IDL.Nat,
            'rank' : Rank,
            'referralEarnings' : IDL.Nat,
            'accumulatedBalance' : IDL.Nat,
            'dailyRoiRate' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getMyDeposits' : IDL.Func([], [IDL.Vec(DepositPublic)], ['query']),
    'getMyInvestments' : IDL.Func([], [IDL.Vec(InvestmentPublic)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserPublic)], ['query']),
    'getMyWithdrawals' : IDL.Func([], [IDL.Vec(WithdrawalPublic)], ['query']),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveWallets' : IDL.Func(
        [],
        [IDL.Vec(CryptoWalletPublic)],
        ['query'],
      ),
    'register' : IDL.Func([RegisterArgs], [IDL.Bool], []),
    'requestWithdrawal' : IDL.Func(
        [RequestWithdrawalArgs],
        [WithdrawalPublic],
        [],
      ),
    'submitDeposit' : IDL.Func([SubmitDepositArgs], [DepositPublic], []),
  });
};

export const init = ({ IDL }) => { return []; };