/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateInvestmentArgs {
  'packageTier' : PackageTier,
  'amount' : bigint,
}
export interface CryptoWalletPublic {
  'id' : WalletId,
  'cryptoName' : string,
  'network' : string,
  'walletAddress' : string,
  'isActive' : boolean,
  'iconUrl' : string,
  'symbol' : string,
}
export type DepositId = bigint;
export interface DepositPublic {
  'id' : DepositId,
  'status' : DepositStatus,
  'packageTier' : PackageTier,
  'userId' : UserId,
  'confirmedAt' : [] | [Timestamp],
  'submittedAt' : Timestamp,
  'walletAddress' : string,
  'adminNote' : [] | [string],
  'amount' : bigint,
  'walletId' : WalletId,
}
export type DepositStatus = { 'REJECTED' : null } |
  { 'PENDING' : null } |
  { 'CONFIRMED' : null };
export type InvestmentId = bigint;
export interface InvestmentPublic {
  'id' : InvestmentId,
  'status' : InvestmentStatus,
  'packageTier' : PackageTier,
  'maturityDate' : Timestamp,
  'userId' : UserId,
  'lastRoiAccrual' : Timestamp,
  'accumulatedBalance' : bigint,
  'amount' : bigint,
  'startDate' : Timestamp,
}
export type InvestmentStatus = { 'MATURED' : null } |
  { 'CANCELLED' : null } |
  { 'ACTIVE' : null };
export type PackageTier = { 'GENESIS' : null } |
  { 'VELOCITY' : null } |
  { 'MOMENTUM' : null };
export type Rank = { 'INFLUENCER' : null } |
  { 'ARBITRAGEUR' : null } |
  { 'NEXUS' : null } |
  { 'APEX' : null } |
  { 'GAME_CHANGER' : null } |
  { 'TRAILBLAZER' : null } |
  { 'VISIONARY' : null } |
  { 'TITAN' : null } |
  { 'CATALYST' : null } |
  { 'LUMINARY' : null } |
  { 'PIONEER' : null } |
  { 'STRATEGIST' : null };
export type ReferralCode = string;
export interface RegisterArgs {
  'referralCode' : [] | [ReferralCode],
  'username' : string,
  'email' : string,
}
export interface RequestWithdrawalArgs {
  'destinationAddress' : string,
  'amount' : bigint,
}
export interface SubmitDepositArgs {
  'packageTier' : PackageTier,
  'amount' : bigint,
  'walletId' : WalletId,
}
export type Timestamp = bigint;
export interface UpsertWalletArgs {
  'cryptoName' : string,
  'network' : string,
  'walletAddress' : string,
  'isActive' : boolean,
  'iconUrl' : string,
  'symbol' : string,
}
export type UserId = Principal;
export interface UserPublic {
  'id' : UserId,
  'referralCode' : ReferralCode,
  'username' : string,
  'email' : string,
  'referredBy' : [] | [UserId],
  'registeredAt' : Timestamp,
}
export type WalletId = bigint;
export type WithdrawalId = bigint;
export interface WithdrawalPublic {
  'id' : WithdrawalId,
  'status' : WithdrawalStatus,
  'userId' : UserId,
  'destinationAddress' : string,
  'processedAt' : [] | [Timestamp],
  'adminNote' : [] | [string],
  'amount' : bigint,
  'requestedAt' : Timestamp,
}
export type WithdrawalStatus = { 'REJECTED' : null } |
  { 'PENDING' : null } |
  { 'APPROVED' : null };
export interface _SERVICE {
  'accrueAllRoi' : ActorMethod<[], undefined>,
  'adminAddAdmin' : ActorMethod<[UserId], undefined>,
  'adminAddWallet' : ActorMethod<[UpsertWalletArgs], CryptoWalletPublic>,
  'adminApproveWithdrawal' : ActorMethod<
    [WithdrawalId, [] | [string]],
    undefined
  >,
  'adminCancelInvestment' : ActorMethod<[InvestmentId], undefined>,
  'adminConfirmDeposit' : ActorMethod<[DepositId, [] | [string]], undefined>,
  'adminCreateInvestment' : ActorMethod<
    [UserId, CreateInvestmentArgs],
    InvestmentPublic
  >,
  'adminDeleteWallet' : ActorMethod<[WalletId], undefined>,
  'adminListAdmins' : ActorMethod<[], Array<UserId>>,
  'adminListAllWallets' : ActorMethod<[], Array<CryptoWalletPublic>>,
  'adminListDeposits' : ActorMethod<[], Array<DepositPublic>>,
  'adminListInvestments' : ActorMethod<[], Array<InvestmentPublic>>,
  'adminListUsers' : ActorMethod<[], Array<UserPublic>>,
  'adminListWithdrawals' : ActorMethod<[], Array<WithdrawalPublic>>,
  'adminRejectDeposit' : ActorMethod<[DepositId, [] | [string]], undefined>,
  'adminRejectWithdrawal' : ActorMethod<
    [WithdrawalId, [] | [string]],
    undefined
  >,
  'adminRemoveAdmin' : ActorMethod<[UserId], undefined>,
  'adminUpdateWallet' : ActorMethod<[WalletId, UpsertWalletArgs], undefined>,
  'getDashboard' : ActorMethod<
    [],
    {
      'referralCode' : ReferralCode,
      'totalInvested' : bigint,
      'rank' : Rank,
      'referralEarnings' : bigint,
      'accumulatedBalance' : bigint,
      'dailyRoiRate' : bigint,
    }
  >,
  'getMyDeposits' : ActorMethod<[], Array<DepositPublic>>,
  'getMyInvestments' : ActorMethod<[], Array<InvestmentPublic>>,
  'getMyProfile' : ActorMethod<[], [] | [UserPublic]>,
  'getMyWithdrawals' : ActorMethod<[], Array<WithdrawalPublic>>,
  'isAdmin' : ActorMethod<[], boolean>,
  'listActiveWallets' : ActorMethod<[], Array<CryptoWalletPublic>>,
  'register' : ActorMethod<[RegisterArgs], boolean>,
  'requestWithdrawal' : ActorMethod<[RequestWithdrawalArgs], WithdrawalPublic>,
  'submitDeposit' : ActorMethod<[SubmitDepositArgs], DepositPublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];