/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RequestWithdrawalArgs {
    destinationAddress: string;
    amount: bigint;
}
export type Timestamp = bigint;
export type InvestmentId = bigint;
export interface UserPublic {
    id: UserId;
    referralCode: ReferralCode;
    username: string;
    email: string;
    referredBy?: UserId;
    registeredAt: Timestamp;
}
export interface WithdrawalPublic {
    id: WithdrawalId;
    status: WithdrawalStatus;
    userId: UserId;
    destinationAddress: string;
    processedAt?: Timestamp;
    adminNote?: string;
    amount: bigint;
    requestedAt: Timestamp;
}
export interface UpsertWalletArgs {
    cryptoName: string;
    network: string;
    walletAddress: string;
    isActive: boolean;
    iconUrl: string;
    symbol: string;
}
export interface RegisterArgs {
    referralCode?: ReferralCode;
    username: string;
    email: string;
}
export interface DepositPublic {
    id: DepositId;
    status: DepositStatus;
    packageTier: PackageTier;
    userId: UserId;
    confirmedAt?: Timestamp;
    submittedAt: Timestamp;
    walletAddress: string;
    adminNote?: string;
    amount: bigint;
    walletId: WalletId;
}
export type WithdrawalId = bigint;
export interface CreateInvestmentArgs {
    packageTier: PackageTier;
    amount: bigint;
}
export type UserId = Principal;
export interface InvestmentPublic {
    id: InvestmentId;
    status: InvestmentStatus;
    packageTier: PackageTier;
    maturityDate: Timestamp;
    userId: UserId;
    lastRoiAccrual: Timestamp;
    accumulatedBalance: bigint;
    amount: bigint;
    startDate: Timestamp;
}
export interface SubmitDepositArgs {
    packageTier: PackageTier;
    amount: bigint;
    walletId: WalletId;
}
export interface CryptoWalletPublic {
    id: WalletId;
    cryptoName: string;
    network: string;
    walletAddress: string;
    isActive: boolean;
    iconUrl: string;
    symbol: string;
}
export type WalletId = bigint;
export type ReferralCode = string;
export type DepositId = bigint;
export enum DepositStatus {
    REJECTED = "REJECTED",
    PENDING = "PENDING",
    CONFIRMED = "CONFIRMED"
}
export enum InvestmentStatus {
    MATURED = "MATURED",
    CANCELLED = "CANCELLED",
    ACTIVE = "ACTIVE"
}
export enum PackageTier {
    GENESIS = "GENESIS",
    VELOCITY = "VELOCITY",
    MOMENTUM = "MOMENTUM"
}
export enum Rank {
    INFLUENCER = "INFLUENCER",
    ARBITRAGEUR = "ARBITRAGEUR",
    NEXUS = "NEXUS",
    APEX = "APEX",
    GAME_CHANGER = "GAME_CHANGER",
    TRAILBLAZER = "TRAILBLAZER",
    VISIONARY = "VISIONARY",
    TITAN = "TITAN",
    CATALYST = "CATALYST",
    LUMINARY = "LUMINARY",
    PIONEER = "PIONEER",
    STRATEGIST = "STRATEGIST"
}
export enum WithdrawalStatus {
    REJECTED = "REJECTED",
    PENDING = "PENDING",
    APPROVED = "APPROVED"
}
export interface backendInterface {
    accrueAllRoi(): Promise<void>;
    adminAddAdmin(newAdmin: UserId): Promise<void>;
    adminAddWallet(args: UpsertWalletArgs): Promise<CryptoWalletPublic>;
    adminApproveWithdrawal(id: WithdrawalId, note: string | null): Promise<void>;
    adminCancelInvestment(id: InvestmentId): Promise<void>;
    adminConfirmDeposit(id: DepositId, note: string | null): Promise<void>;
    adminCreateInvestment(userId: UserId, args: CreateInvestmentArgs): Promise<InvestmentPublic>;
    adminDeleteWallet(id: WalletId): Promise<void>;
    adminListAdmins(): Promise<Array<UserId>>;
    adminListAllWallets(): Promise<Array<CryptoWalletPublic>>;
    adminListDeposits(): Promise<Array<DepositPublic>>;
    adminListInvestments(): Promise<Array<InvestmentPublic>>;
    adminListUsers(): Promise<Array<UserPublic>>;
    adminListWithdrawals(): Promise<Array<WithdrawalPublic>>;
    adminRejectDeposit(id: DepositId, note: string | null): Promise<void>;
    adminRejectWithdrawal(id: WithdrawalId, note: string | null): Promise<void>;
    adminRemoveAdmin(target: UserId): Promise<void>;
    adminUpdateWallet(id: WalletId, args: UpsertWalletArgs): Promise<void>;
    getDashboard(): Promise<{
        referralCode: ReferralCode;
        totalInvested: bigint;
        rank: Rank;
        referralEarnings: bigint;
        accumulatedBalance: bigint;
        dailyRoiRate: bigint;
    }>;
    getMyDeposits(): Promise<Array<DepositPublic>>;
    getMyInvestments(): Promise<Array<InvestmentPublic>>;
    getMyProfile(): Promise<UserPublic | null>;
    getMyWithdrawals(): Promise<Array<WithdrawalPublic>>;
    isAdmin(): Promise<boolean>;
    listActiveWallets(): Promise<Array<CryptoWalletPublic>>;
    register(args: RegisterArgs): Promise<boolean>;
    requestWithdrawal(args: RequestWithdrawalArgs): Promise<WithdrawalPublic>;
    submitDeposit(args: SubmitDepositArgs): Promise<DepositPublic>;
}
import type { CreateInvestmentArgs as _CreateInvestmentArgs, DepositId as _DepositId, DepositPublic as _DepositPublic, DepositStatus as _DepositStatus, InvestmentId as _InvestmentId, InvestmentPublic as _InvestmentPublic, InvestmentStatus as _InvestmentStatus, PackageTier as _PackageTier, Rank as _Rank, ReferralCode as _ReferralCode, RegisterArgs as _RegisterArgs, SubmitDepositArgs as _SubmitDepositArgs, Timestamp as _Timestamp, UserId as _UserId, UserPublic as _UserPublic, WalletId as _WalletId, WithdrawalId as _WithdrawalId, WithdrawalPublic as _WithdrawalPublic, WithdrawalStatus as _WithdrawalStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async accrueAllRoi(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.accrueAllRoi();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.accrueAllRoi();
            return result;
        }
    }
    async adminAddAdmin(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddAdmin(arg0);
            return result;
        }
    }
    async adminAddWallet(arg0: UpsertWalletArgs): Promise<CryptoWalletPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddWallet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddWallet(arg0);
            return result;
        }
    }
    async adminApproveWithdrawal(arg0: WithdrawalId, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveWithdrawal(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveWithdrawal(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminCancelInvestment(arg0: InvestmentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCancelInvestment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCancelInvestment(arg0);
            return result;
        }
    }
    async adminConfirmDeposit(arg0: DepositId, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminConfirmDeposit(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminConfirmDeposit(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminCreateInvestment(arg0: UserId, arg1: CreateInvestmentArgs): Promise<InvestmentPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.adminCreateInvestment(arg0, to_candid_CreateInvestmentArgs_n2(this._uploadFile, this._downloadFile, arg1));
                return from_candid_InvestmentPublic_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminCreateInvestment(arg0, to_candid_CreateInvestmentArgs_n2(this._uploadFile, this._downloadFile, arg1));
            return from_candid_InvestmentPublic_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminDeleteWallet(arg0: WalletId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteWallet(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteWallet(arg0);
            return result;
        }
    }
    async adminListAdmins(): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAdmins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAdmins();
            return result;
        }
    }
    async adminListAllWallets(): Promise<Array<CryptoWalletPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListAllWallets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListAllWallets();
            return result;
        }
    }
    async adminListDeposits(): Promise<Array<DepositPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListDeposits();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListDeposits();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListInvestments(): Promise<Array<InvestmentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListInvestments();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListInvestments();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListUsers(): Promise<Array<UserPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListUsers();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListUsers();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListWithdrawals(): Promise<Array<WithdrawalPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListWithdrawals();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListWithdrawals();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminRejectDeposit(arg0: DepositId, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectDeposit(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectDeposit(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminRejectWithdrawal(arg0: WithdrawalId, arg1: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectWithdrawal(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectWithdrawal(arg0, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminRemoveAdmin(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRemoveAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRemoveAdmin(arg0);
            return result;
        }
    }
    async adminUpdateWallet(arg0: WalletId, arg1: UpsertWalletArgs): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateWallet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateWallet(arg0, arg1);
            return result;
        }
    }
    async getDashboard(): Promise<{
        referralCode: ReferralCode;
        totalInvested: bigint;
        rank: Rank;
        referralEarnings: bigint;
        accumulatedBalance: bigint;
        dailyRoiRate: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboard();
                return from_candid_record_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboard();
            return from_candid_record_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDeposits(): Promise<Array<DepositPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDeposits();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDeposits();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInvestments(): Promise<Array<InvestmentPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInvestments();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInvestments();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWithdrawals(): Promise<Array<WithdrawalPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWithdrawals();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWithdrawals();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isAdmin();
            return result;
        }
    }
    async listActiveWallets(): Promise<Array<CryptoWalletPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveWallets();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveWallets();
            return result;
        }
    }
    async register(arg0: RegisterArgs): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.register(to_candid_RegisterArgs_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.register(to_candid_RegisterArgs_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async requestWithdrawal(arg0: RequestWithdrawalArgs): Promise<WithdrawalPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.requestWithdrawal(arg0);
                return from_candid_WithdrawalPublic_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestWithdrawal(arg0);
            return from_candid_WithdrawalPublic_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitDeposit(arg0: SubmitDepositArgs): Promise<DepositPublic> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDeposit(to_candid_SubmitDepositArgs_n35(this._uploadFile, this._downloadFile, arg0));
                return from_candid_DepositPublic_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDeposit(to_candid_SubmitDepositArgs_n35(this._uploadFile, this._downloadFile, arg0));
            return from_candid_DepositPublic_n13(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_DepositPublic_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositPublic): DepositPublic {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_DepositStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DepositStatus): DepositStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_InvestmentPublic_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvestmentPublic): InvestmentPublic {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_InvestmentStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvestmentStatus): InvestmentStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_PackageTier_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PackageTier): PackageTier {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Rank_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Rank): Rank {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserPublic_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserPublic): UserPublic {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalPublic_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalPublic): WithdrawalPublic {
    return from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_WithdrawalStatus_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WithdrawalStatus): WithdrawalStatus {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserId]): UserId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserPublic]): UserPublic | null {
    return value.length === 0 ? null : from_candid_UserPublic_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _DepositId;
    status: _DepositStatus;
    packageTier: _PackageTier;
    userId: _UserId;
    confirmedAt: [] | [_Timestamp];
    submittedAt: _Timestamp;
    walletAddress: string;
    adminNote: [] | [string];
    amount: bigint;
    walletId: _WalletId;
}): {
    id: DepositId;
    status: DepositStatus;
    packageTier: PackageTier;
    userId: UserId;
    confirmedAt?: Timestamp;
    submittedAt: Timestamp;
    walletAddress: string;
    adminNote?: string;
    amount: bigint;
    walletId: WalletId;
} {
    return {
        id: value.id,
        status: from_candid_DepositStatus_n15(_uploadFile, _downloadFile, value.status),
        packageTier: from_candid_PackageTier_n10(_uploadFile, _downloadFile, value.packageTier),
        userId: value.userId,
        confirmedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.confirmedAt)),
        submittedAt: value.submittedAt,
        walletAddress: value.walletAddress,
        adminNote: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.adminNote)),
        amount: value.amount,
        walletId: value.walletId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    referralCode: _ReferralCode;
    username: string;
    email: string;
    referredBy: [] | [_UserId];
    registeredAt: _Timestamp;
}): {
    id: UserId;
    referralCode: ReferralCode;
    username: string;
    email: string;
    referredBy?: UserId;
    registeredAt: Timestamp;
} {
    return {
        id: value.id,
        referralCode: value.referralCode,
        username: value.username,
        email: value.email,
        referredBy: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.referredBy)),
        registeredAt: value.registeredAt
    };
}
function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WithdrawalId;
    status: _WithdrawalStatus;
    userId: _UserId;
    destinationAddress: string;
    processedAt: [] | [_Timestamp];
    adminNote: [] | [string];
    amount: bigint;
    requestedAt: _Timestamp;
}): {
    id: WithdrawalId;
    status: WithdrawalStatus;
    userId: UserId;
    destinationAddress: string;
    processedAt?: Timestamp;
    adminNote?: string;
    amount: bigint;
    requestedAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_WithdrawalStatus_n27(_uploadFile, _downloadFile, value.status),
        userId: value.userId,
        destinationAddress: value.destinationAddress,
        processedAt: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.processedAt)),
        adminNote: record_opt_to_undefined(from_candid_opt_n18(_uploadFile, _downloadFile, value.adminNote)),
        amount: value.amount,
        requestedAt: value.requestedAt
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode: _ReferralCode;
    totalInvested: bigint;
    rank: _Rank;
    referralEarnings: bigint;
    accumulatedBalance: bigint;
    dailyRoiRate: bigint;
}): {
    referralCode: ReferralCode;
    totalInvested: bigint;
    rank: Rank;
    referralEarnings: bigint;
    accumulatedBalance: bigint;
    dailyRoiRate: bigint;
} {
    return {
        referralCode: value.referralCode,
        totalInvested: value.totalInvested,
        rank: from_candid_Rank_n30(_uploadFile, _downloadFile, value.rank),
        referralEarnings: value.referralEarnings,
        accumulatedBalance: value.accumulatedBalance,
        dailyRoiRate: value.dailyRoiRate
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _InvestmentId;
    status: _InvestmentStatus;
    packageTier: _PackageTier;
    maturityDate: _Timestamp;
    userId: _UserId;
    lastRoiAccrual: _Timestamp;
    accumulatedBalance: bigint;
    amount: bigint;
    startDate: _Timestamp;
}): {
    id: InvestmentId;
    status: InvestmentStatus;
    packageTier: PackageTier;
    maturityDate: Timestamp;
    userId: UserId;
    lastRoiAccrual: Timestamp;
    accumulatedBalance: bigint;
    amount: bigint;
    startDate: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_InvestmentStatus_n8(_uploadFile, _downloadFile, value.status),
        packageTier: from_candid_PackageTier_n10(_uploadFile, _downloadFile, value.packageTier),
        maturityDate: value.maturityDate,
        userId: value.userId,
        lastRoiAccrual: value.lastRoiAccrual,
        accumulatedBalance: value.accumulatedBalance,
        amount: value.amount,
        startDate: value.startDate
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    GENESIS: null;
} | {
    VELOCITY: null;
} | {
    MOMENTUM: null;
}): PackageTier {
    return "GENESIS" in value ? PackageTier.GENESIS : "VELOCITY" in value ? PackageTier.VELOCITY : "MOMENTUM" in value ? PackageTier.MOMENTUM : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    REJECTED: null;
} | {
    PENDING: null;
} | {
    CONFIRMED: null;
}): DepositStatus {
    return "REJECTED" in value ? DepositStatus.REJECTED : "PENDING" in value ? DepositStatus.PENDING : "CONFIRMED" in value ? DepositStatus.CONFIRMED : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    REJECTED: null;
} | {
    PENDING: null;
} | {
    APPROVED: null;
}): WithdrawalStatus {
    return "REJECTED" in value ? WithdrawalStatus.REJECTED : "PENDING" in value ? WithdrawalStatus.PENDING : "APPROVED" in value ? WithdrawalStatus.APPROVED : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    INFLUENCER: null;
} | {
    ARBITRAGEUR: null;
} | {
    NEXUS: null;
} | {
    APEX: null;
} | {
    GAME_CHANGER: null;
} | {
    TRAILBLAZER: null;
} | {
    VISIONARY: null;
} | {
    TITAN: null;
} | {
    CATALYST: null;
} | {
    LUMINARY: null;
} | {
    PIONEER: null;
} | {
    STRATEGIST: null;
}): Rank {
    return "INFLUENCER" in value ? Rank.INFLUENCER : "ARBITRAGEUR" in value ? Rank.ARBITRAGEUR : "NEXUS" in value ? Rank.NEXUS : "APEX" in value ? Rank.APEX : "GAME_CHANGER" in value ? Rank.GAME_CHANGER : "TRAILBLAZER" in value ? Rank.TRAILBLAZER : "VISIONARY" in value ? Rank.VISIONARY : "TITAN" in value ? Rank.TITAN : "CATALYST" in value ? Rank.CATALYST : "LUMINARY" in value ? Rank.LUMINARY : "PIONEER" in value ? Rank.PIONEER : "STRATEGIST" in value ? Rank.STRATEGIST : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    MATURED: null;
} | {
    CANCELLED: null;
} | {
    ACTIVE: null;
}): InvestmentStatus {
    return "MATURED" in value ? InvestmentStatus.MATURED : "CANCELLED" in value ? InvestmentStatus.CANCELLED : "ACTIVE" in value ? InvestmentStatus.ACTIVE : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DepositPublic>): Array<DepositPublic> {
    return value.map((x)=>from_candid_DepositPublic_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvestmentPublic>): Array<InvestmentPublic> {
    return value.map((x)=>from_candid_InvestmentPublic_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserPublic>): Array<UserPublic> {
    return value.map((x)=>from_candid_UserPublic_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WithdrawalPublic>): Array<WithdrawalPublic> {
    return value.map((x)=>from_candid_WithdrawalPublic_n25(_uploadFile, _downloadFile, x));
}
function to_candid_CreateInvestmentArgs_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateInvestmentArgs): _CreateInvestmentArgs {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_PackageTier_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PackageTier): _PackageTier {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_RegisterArgs_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RegisterArgs): _RegisterArgs {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_SubmitDepositArgs_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubmitDepositArgs): _SubmitDepositArgs {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    packageTier: PackageTier;
    amount: bigint;
}): {
    packageTier: _PackageTier;
    amount: bigint;
} {
    return {
        packageTier: to_candid_PackageTier_n4(_uploadFile, _downloadFile, value.packageTier),
        amount: value.amount
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    referralCode?: ReferralCode;
    username: string;
    email: string;
}): {
    referralCode: [] | [_ReferralCode];
    username: string;
    email: string;
} {
    return {
        referralCode: value.referralCode ? candid_some(value.referralCode) : candid_none(),
        username: value.username,
        email: value.email
    };
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    packageTier: PackageTier;
    amount: bigint;
    walletId: WalletId;
}): {
    packageTier: _PackageTier;
    amount: bigint;
    walletId: _WalletId;
} {
    return {
        packageTier: to_candid_PackageTier_n4(_uploadFile, _downloadFile, value.packageTier),
        amount: value.amount,
        walletId: value.walletId
    };
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PackageTier): {
    GENESIS: null;
} | {
    VELOCITY: null;
} | {
    MOMENTUM: null;
} {
    return value == PackageTier.GENESIS ? {
        GENESIS: null
    } : value == PackageTier.VELOCITY ? {
        VELOCITY: null
    } : value == PackageTier.MOMENTUM ? {
        MOMENTUM: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
